cafe/urls.py
from django.contrib import admin as admin_
from admin import *

from admin import urls as adminUrls
from manager import urls as managerUrls

from django.conf.urls import *
from cafe import views
from django.conf import settings
from django.urls import path, re_path, include
from django.contrib.auth.views import logout
from django.contrib.auth import views as django_auth_views
from django.contrib.auth import urls as authUrls

import rest_framework_jwt
#from rest_framework_jwt import views as rest_framework_jwt_views

from ingredients import views as ingredientsViews
from dishes import views as dishesViews
from _auth import views as authViews
from cafes import views as cafesViews
from authentication import views as authenticationViews
from statistics_ import views as statisticsViews

urlpatterns = [
    path('admin/', admin_.site.urls),
    #path('admin/', include(adminUrls.urlpatterns)),
    path("manager/", include(managerUrls.urlpatterns)),
    url(r"^add-ingredient/$", ingredientsViews.ingredient, name="add-ingredient"),
    url(r"^add-ingredientName/$", ingredientsViews.ingredientName, name="add-ingredientName"),
    url(r"^add-dish/$", dishesViews.addDish, name="add-dish"),
    url(r"^menu/$", dishesViews.dishesList, name="menu"),
    url(r"^dish/$", dishesViews.dishDescription, name="dishDescription"),
    url(r"^cart/$", dishesViews.cart, name="cart"),
    url(r"^accept-order/$", dishesViews.acceptOrder, name="acceptOrder"),
    path("order-details/<int:id>/", dishesViews.orderDetails, name="orderDetails"),
    url(r"^$", views.home, name="home"),

    # path("dish/", dishesViews.Dishes.as_view(), name="dish"),
    path("api/courier/orders_list/", dishesViews.OrdersListForCourier.as_view()),
    path("api/courier/order_details/<int:id>/", dishesViews.OrderDetailsForCourier.as_view()),
    path("api/courier/take_order/<int:id>/", dishesViews.CourierTakeOrder.as_view()),
    path("api/courier/cancel_order/<int:id>/", dishesViews.CourierCancelOrder.as_view()),
    path("api/courier/update_location/", dishesViews.CourierUpdateLocation.as_view()),
    path("api/courier/order/submit/<int:id>/", dishesViews.CourierSubmitOrder.as_view()),
    path("api/courier/order/my/", dishesViews.CourierMyOrders.as_view()),
    path("api/courier/order/total/", dishesViews.CourierTotalOrders.as_view()),

    path("api/courier/ingredients_transit_list/", dishesViews.IngredientsTransitListForCourier.as_view()),
    path("api/courier/ingredients_transit_details/<int:id>/", dishesViews.IngredientsTransitDetailsForCourier.as_view()),
    path("api/courier/take_ingredients_transit/<int:id>/", dishesViews.CourierTakeIngrTransit.as_view()),
    path("api/courier/cancel_ingredients_transit/<int:id>/", dishesViews.CourierCancelIngrTransit.as_view()),
    path("api/courier/ingredients_transit/total/", dishesViews.CourierTotalIngrTransit.as_view()),

    path("api/menu/dishes_list/<int:page>/", dishesViews.DishesList.as_view()),
    path("api/menu/categories_list/", dishesViews.DishCategoriesList.as_view()),
    path("api/menu/dish_description/<int:id>/", dishesViews.DishDetails.as_view()),

    path("api/order/create/", dishesViews.CreateOrder.as_view(), name="createOrder"),

    path("api/user/data/", authViews.UserData.as_view()),

    path("api/statistics/get/", statisticsViews.GetStatistics.as_view(), name="managerStatisticsGet"),


    url(r"^api/dish/$", dishesViews.api, name="apiDish"),
    url(r"^api/ingredient/$", ingredientsViews.api, name="apiIngredient"),

    url(r"^api/auth/", include("djoser.urls")),
    url(r"^api/auth/", include("djoser.urls.authtoken")),
    url(r"^api/auth/", include("djoser.urls.jwt")),
    #url(r"^api/auth/token/login1/", authenticationViews.token_request),

    url(r"^user/signup/$", authViews.signup, name="signup"),
    url(r"^user/login/$", django_auth_views.login, {'template_name': 'login.html'}, name="login"),
    url(r"^user/logout/$", logout, {"next_page": "/"}, name="logout"),
    url(r"^user/profile/$", authViews.profile, name="profile"),

    path('test/<int:id>/', dishesViews.test, name='room'),
    #url(r"^api/token/login/$", authenticationViews.CustomTokenCreateView.as_view()),


    # url(r"^api/login/$", rest_framework_jwt.views.obtain_jwt_token, name="apiLogin"),
]

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

manager/urls.py
from . import views
from statistics_ import views as statisticsViews

from django.conf import settings
from django.urls import path, re_path, include
from django.conf.urls import *


urlpatterns = [
    url(r"^$", views.home, name="managerHome"),
    path("order/list/<int:page>/", views.ordersList, name="managerOrdersList"),
    path("order/details/<int:id>/", views.orderDetails, name="managerOrderDetails"),

    path("prepared-dish/list/<int:page>/", views.preparedDishesList, name="managerPreparedDishesList"),
    path("prepared-dish/details/<int:id>/", views.preparedDishDetails, name="managerPreparedDishDetails"),
    path("prepared-dish/add/", views.preparedDishAdd, name="managerPreparedDishAdd"),

    path("ingredient/list/<int:page>/", views.ingredientsList, name="managerIngredientsList"),
    path("ingredient/add/", views.ingredientAdd, name="managerIngredientAdd"),
    path("ingredient/edit/<int:id>/", views.ingredientEdit, name="managerIngredientEdit"),

    path("ingredient-name/add/", views.ingredientNameAdd, name="managerIngredientNameAdd"),
    path("ingredient-name/edit/<int:id>/", views.ingredientNameEdit, name="managerIngredientNameEdit"),
    path("ingredient-name/get-units/<int:id>/", views.getIngredientNameUnits.as_view(), name="managerIngredientNameGetUnits"),

    path("statistics/", views.statistics, name="managerStatistics"),

    path("dish/list/<int:page>/", views.dishesList, name="managerDishesList"),
    path("dish/add/", views.dishAdd, name="managerDishAdd"),
    path("dish/edit/<int:id>/", views.dishEdit, name="managerDishEdit"),

    path("ingredient-transit/list/<int:page>/", views.ingrTransitList, name="managerIngrTransitList"),
    path("ingredient-transit/add/", views.ingrTransitAdd, name="managerIngrTransitAdd"),
    path("ingredient-transit/submit/<int:id>/", views.ingrTransitSubmit, name="managerIngrTransitSubmit"),
    # path("dish/edit/<int:id>/", views.ingredientEdit, name="managerIngredientEdit"),
]

dishes/models.py
from django.db import models
from django.utils.deconstruct import deconstructible
#from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
import os
import sys
from cafe import settings
import string
import random
from django.utils.timezone import now as time_now

from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile
from resizeimage import resizeimage
from django.core.validators import FileExtensionValidator

from ingredients.models import Units
from cafes.models import Cafe

from ingredients.models import IngredientName, Ingredient
from locations.models import Location

# def get_sentinel_user():
#     return get_user_model().objects.get_or_create(username = 'Удалённый пользователь')[0]

# @deconstructible
# class Rename(object):
#     '''
#     Генерирует название файла, возвращает полный путь к файлу
#     '''
#     def __init__(self, sub_path):
#         self.path = sub_path
#
#     def __call__(self, instance, filename):
#         print('RENAME CALLED')
#         new_path = ''
#         fullpath = ''
#         while not fullpath or os.path.isfile(fullpath):
#             print(fullpath)
#             ext = filename.split(".")[-1]
#             random_name = ''.join([random.choice(string.ascii_letters + string.digits) for n in range(12)])
#             new_filename = random_name + ".%s" % ext
#             new_path = os.path.join(self.path, new_filename)
#             fullpath = os.path.join(settings.MEDIA_ROOT, new_path)
#
#         return new_path


def Rename(filename, path):
    print('RENAME CALLED')
    random_name = ''
    fullpath = ''
    ext = filename.split(".")[-1]

    while not fullpath or os.path.isfile(fullpath):
        print(fullpath)
        random_name = ''.join([random.choice(string.ascii_letters + string.digits) for n in range(12)])
        new_filename = random_name + ".%s" % ext
        new_path = os.path.join(path, new_filename)
        fullpath = os.path.join(settings.MEDIA_ROOT, new_path)

    return (random_name, ext)



class CategoryName(models.Model):
    name = models.CharField("Назва", unique=True, max_length=40)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Назва категорії"
        verbose_name_plural = "Назви категорій"
        ordering = ('name',)

class Category(models.Model):
    category = models.ForeignKey("CategoryName", models.CASCADE)
    dish = models.ForeignKey("Dish", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Категорія"
        verbose_name_plural = "Категорії"
        ordering = ()


class Dish(models.Model):
    name  = models.CharField("Назва", unique=True, max_length=150)
    image = models.ImageField("Зображення", upload_to="added/dishes/", default="added/dishes/default.jpg", validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])
    description = models.TextField("Опис")
    calorie = models.FloatField("Калорійність (кал)", default=1.0)
    weight  = models.FloatField("Маса (г)", default=1.0)
    price = models.FloatField("Цiна", default=0, blank=True)
    cooking_time = models.IntegerField("Час приготування", default=1, blank=False, null=False)
    prepared_lifetime = models.IntegerField("Термін придатності заготовленої страви (хв)", null=True, default=60)
    prepared_cooking_time = models.IntegerField("Час приготування заготовленої страви", null=True, default=None)
    is_active = models.BooleanField("Чи активне", default=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        print("SAVE STARTED")
        from time import sleep

        try:
            old_image = Dish.objects.filter(id=self.id)[0].image
        except Exception:
            old_image = None
        pil_image_obj = Image.open(self.image)
        try:
            new_image = resizeimage.resize_width(pil_image_obj, 1920)
        except: # если ширина картинки меньше необходимой
            new_image = pil_image_obj

        temp_name = self.image.name
        format = "JPEG" if temp_name.split('.')[-1].strip() in ("jpg", "jpeg") else "PNG"

        new_image_io = BytesIO()
        new_image = new_image.convert("RGB")
        new_image.save(new_image_io, format=format)

        # new_image_min_io = BytesIO()
        # new_image_min = new_image_min.convert("RGB")
        # new_image_min.save(new_image_min_io, format=format)

        if old_image:
            full_old_img_path = os.path.join(settings.MEDIA_ROOT, old_image.name)

            if os.path.isfile(full_old_img_path):
                # удаление основного изображения
                try:
                    os.remove(full_old_img_path)
                except Exception:
                    pass
                # удаление уменьшенного изображения
                # try:
                #     old_image_path_parts = old_image.name.split('.')
                #     os.remove(old_image_path_parts[:-1] + '.min.' + old_image_path_parts[-1])
                # except Exception:
                #     pass

        self.image.delete(save=False)

        # self.image.save(
        #     name=temp_name + 'asd',
        #     content=ContentFile(new_image_io.getvalue()),
        #     save=False
        # )
        newNameTuple = Rename(temp_name, "added/dishes/")
        newName = newNameTuple[0]
        fileExt = newNameTuple[1]
        print('new_name', newName)
        print("SAVING...")
        self.image.save(
            name="%s.%s" % (newName, fileExt),
            content=ContentFile(new_image_io.getvalue()),
            save=False
        )
        print("SAVED")

        super(Dish, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Страва"
        verbose_name_plural = "Список страв"
        ordering = ('name',)


class DishIngredients(models.Model):
    dish = models.ForeignKey(Dish, verbose_name="Страва", on_delete=models.CASCADE)
    ingredient = models.ForeignKey(IngredientName, verbose_name="Iнгредієнт", on_delete=models.CASCADE)
    amount = models.IntegerField("К-ть", blank=True, default=1)

    def __str__(self):
        return self.dish.name

    def save(self, *args, **kwargs):
        if self.amount == None:
            self.amount = 1

        super(DishIngredients, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Інгредієнт"
        verbose_name_plural = "Інгредієнти"
        unique_together = ("dish", "ingredient")

class DishInCart(models.Model):
    dish = models.ForeignKey("Dish", verbose_name="Страва", on_delete=models.CASCADE, null=True)
    qty  = models.IntegerField("Кiлькiсть", default=1)
    user = models.ForeignKey(User, verbose_name="Користувач", on_delete=models.CASCADE, blank=True, null=True)
    user_cookie = models.CharField("User Hash", max_length=20, blank=True, null=True)

    def __str__(self):
        try:
            return self.dish.name
        except:
            return ""

    class Meta:
        verbose_name = "Cтрава в кошику"
        verbose_name_plural = "Список страв в кошиках"
        ordering = ('dish',)
        unique_together = ("dish", "user", "user_cookie")


class Order(models.Model):
    STATUSES = (
        ("in_process", "В обробці"),
        ("done", "Виконано")
    )
    user = models.ForeignKey(User, verbose_name="Замовник", on_delete=models.CASCADE)
    location = models.ForeignKey(Location, verbose_name="Локація", null=True, default=None, on_delete=models.PROTECT)
    datetime = models.DateTimeField("Дата замовлення", default=time_now)
    total_cost = models.FloatField("Загальна вартість", default=1, blank=True, null=True)
    status = models.CharField("Статус", choices=STATUSES, max_length=len(STATUSES[0][0]), null=True, default=STATUSES[0][0], blank=True)

    def __str__(self):
        return "Замовлення #%d" % self.id

    class Meta:
        verbose_name = "Замовлення"
        verbose_name_plural = "Список замовлень"
        ordering = ("datetime", "user", "total_cost")

class DishInOrder(models.Model):
    order = models.ForeignKey("Order", on_delete=models.CASCADE)
    dish  = models.ForeignKey("Dish", verbose_name="Страва", on_delete=models.SET(None), null=True)
    qty   = models.IntegerField("Кiлькiсть", default=1)

    def __str__(self):
        return "Об'єкт %s" % self.order.__str__

    class Meta:
        verbose_name = "Cтрава в замовленнi"
        verbose_name_plural = "Список страв в замовленнях"
        ordering = ('dish',)
        unique_together = ("order", "dish",)

class PreparedDish(models.Model):
    dish  = models.ForeignKey("Dish", verbose_name="Страва", on_delete=models.CASCADE, null=True)
    cafe = models.ForeignKey(Cafe, verbose_name="Кафе", on_delete=models.PROTECT, null=True)
    qty = models.IntegerField("Кiлькiсть", default=1)
    add_time = models.DateTimeField("Додано", null=True, editable=False, default=time_now)

    def __str__(self):
        try:
            return "Заготовлена страва %s" % self.dish.name
        except Exception:
            return "Заготовлена страва %d" % self.id

    class Meta:
        verbose_name = "Заготовлена страва"
        verbose_name_plural = "Заготовленi страви"


class PreparedDishesUsed(models.Model):
    ordered_dish = models.ForeignKey("DishInOrderForCafe", on_delete=models.CASCADE)
    prepared_dish = models.ForeignKey("PreparedDish", on_delete=models.SET(None), default=None, null=True)
    qty = models.IntegerField("Скiльки заготовлених використано", default=0)

    def __str__(self):
        return "Об'єкт %s" % self.ordered_dish.__str__

    class Meta:
        verbose_name = "Використана заготовлена страва"
        verbose_name_plural = "Використанi заготовленi страви"



manager/models.py
from django.db import models

# Create your models here.

statistics_/models.py
from django.db import models
from django.utils.timezone import now as time_now

class Statistics(models.Model):
    date = models.DateField("дата", default=time_now, unique=True)
    ordered_dishes_qty = models.IntegerField("к-ть замовлених страв", default=0)
    bought_ingredients = models.FloatField("вартiсть замовлених інгредієнтів", default=0)
    used_ingredients = models.FloatField("вартiсть витрачених інгредієнтів", default=0)
    overdued_ingredients = models.FloatField("вартiсть зіпсованих інгредієнтів", default=0)
    total_profit = models.FloatField("сума прибутку", default=0)

    def __str__(self):
        return str(self.date)

    class Meta:
        verbose_name = "статистика"
        verbose_name_plural = "статистика"

templates/manager/dish-add.html
{% extends "manager/base.html" %}
{% load static %}

{% block add_media %}
{% endblock %}

{% block content %}
    <h1>Додати страву</h1>

    <div class="row flex-grow">
        <div class="col-12">
          <div class="card">
            <div class="card-body col-6">
                <form action="" method="POST" id="dishForm" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="name">Назва</label>

                        {% if dish.name.errors %}
                            <ul class="list-ticked text-small">
                            {% for error in dish.name.errors %}
                                <li class="text-danger"><span>{{ error|escape }}</span></li>
                            {% endfor %}
                            </ul>
                        {% endif %}

                        <input type="text" class="form-control" id="id_name" name="name"
                               value="{% if dish.name.value %}{{ dish.name.value|toStr|ifNone:"" }}{% endif %}">
                    </div>

                    <div class="form-group">
                        <label for="image">Зображення</label>

                        {% if dish.image.errors %}
                            <ul class="list-ticked text-small">
                            {% for error in dish.image.errors %}
                                <li class="text-danger"><span>{{ error|escape }}</span></li>
                            {% endfor %}
                            </ul>
                        {% endif %}

                        <div class="input-group">
                            {% if dish.image.value %}<div class="col-12"><a href="/{{ dish.image.value }}" target="_blank" class="text-small">{{ dish.image.value }}</a></div>{% endif %}
                            <div class=""><input type="file" class="form-control" id="id_image" name="image" accept="image/x-png,image/jpeg"></div> {# {% if dish.image.value %}{{ dish.image.value|toStr|ifNone:"" }}{% endif %} #}
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="cafe">Опис</label>

                        {% if dish.cafe.errors %}
                            <ul class="list-ticked text-small">
                            {% for error in dish.cafe.errors %}
                                <li class="text-danger"><span>{{ error|escape }}</span></li>
                            {% endfor %}
                            </ul>
                        {% endif %}

                        
                        <textarea class="form-control" rows="12" id="id_description" name="description"
                        >{% if dish.description.value %}{{ dish.description.value|toStr|ifNone:"" }}{% endif %}</textarea>
                    </div>


                    <div class="form-group">
                        <label for="weight">Маса</label>

                        {% if dish.weight.errors %}
                            <ul class="list-ticked text-small">
                            {% for error in dish.weight.errors %}
                                <li class="text-danger"><span>{{ error|escape }}</span></li>
                            {% endfor %}
                            </ul>
                        {% endif %}

                        <div class="input-group">
                            <input type="number" class="form-control" id="id_weight" name="weight"
                                   value="{% if dish.weight.value %}{{ dish.weight.value|toStr }}{% endif %}">
                            <div class="input-group-append">
                                <span class="input-group-text">г</span>
                            </div>
                        </div>
                    </div>



                    <div class="form-group">
                        <label for="calorie">Калорійність</label>

                        {% if dish.calorie.errors %}
                            <ul class="list-ticked text-small">
                            {% for error in dish.calorie.errors %}
                                <li class="text-danger"><span>{{ error|escape }}</span></li>
                            {% endfor %}
                            </ul>
                        {% endif %}

                        <div class="input-group">
                            <input type="number" class="form-control" id="id_calorie" name="calorie"
                                   value="{% if dish.calorie.value %}{{ dish.calorie.value|toStr }}{% endif %}">
                            <div class="input-group-append">
                                <span class="input-group-text">кал</span>
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="cooking_time">Час приготування</label>

                        {% if dish.cooking_time.errors %}
                            <ul class="list-ticked text-small">
                            {% for error in dish.cooking_time.errors %}
                                <li class="text-danger"><span>{{ error|escape }}</span></li>
                            {% endfor %}
                            </ul>
                        {% endif %}

                        <div class="input-group">
                            <input type="number" class="form-control" id="id_cooking_time" name="cooking_time"
                                   value="{% if dish.cooking_time.value %}{{ dish.cooking_time.value|toStr }}{% endif %}">
                            <div class="input-group-append">
                                <span class="input-group-text">хв</span>
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="prepared_cooking_time">Час приготування заготовленої страви</label>

                        {% if dish.prepared_cooking_time.errors %}
                            <ul class="list-ticked text-small">
                            {% for error in dish.prepared_cooking_time.errors %}
                                <li class="text-danger"><span>{{ error|escape }}</span></li>
                            {% endfor %}
                            </ul>
                        {% endif %}

                        <div class="input-group">
                            <input type="number" class="form-control" id="id_prepared_cooking_time" name="prepared_cooking_time"
                                   value="{% if dish.prepared_cooking_time.value %}{{ dish.prepared_cooking_time.value|toStr }}{% endif %}">
                            <div class="input-group-append">
                                <span class="input-group-text">хв</span>
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="prepared_lifetime">Термін придатності заготовленої страви</label>

                        {% if dish.prepared_lifetime.errors %}
                            <ul class="list-ticked text-small">
                            {% for error in dish.prepared_lifetime.errors %}
                                <li class="text-danger"><span>{{ error|escape }}</span></li>
                            {% endfor %}
                            </ul>
                        {% endif %}

                        <div class="input-group">
                            <input type="number" class="form-control" id="id_prepared_lifetime" name="prepared_lifetime"
                                   value="{% if dish.prepared_lifetime.value %}{{ dish.prepared_lifetime.value|toStr }}{% endif %}">
                            <div class="input-group-append">
                                <span class="input-group-text">хв</span>
                            </div>
                        </div>
                    </div>



                    <div class="form-group">
                        <label for="price">Ціна</label>

                        {% if dish.price.errors %}
                            <ul class="list-ticked text-small">
                            {% for error in dish.price.errors %}
                                <li class="text-danger"><span>{{ error|escape }}</span></li>
                            {% endfor %}
                            </ul>
                        {% endif %}

                        <div class="input-group">
                            <input type="number" class="form-control" id="price" name="price" placeholder="30.40"
                                value="{% if dish.price.value %}{{ dish.price.value|toStr|ifNone:"" }}{% endif %}">
                            <div class="input-group-append">
                                <span class="input-group-text"><span class="sellingUnits">грн</span></span>
                            </div>
                        </div>
                    </div>



                    <br>
                    <div class="form-group">
                        <h4>Iнгредієнти</h4>
                        <table class="table">
                            {{ formset.management_form }}

                            {% for form in formset.forms %}
                                {% if forloop.first %}
                                    <thead>
                                    <tr>
                                        {% for field in form.visible_fields %}
                                            <th>{{ field.label|capfirst }}</th>
                                        {% endfor %}
                                    </tr>
                                    </thead>
                                {% endif %}
                                <tr class="ingredient formset_row">
                                    {% for field in form.visible_fields %}
                                        <td>
                                            {# Include the hidden fields in the form #}
                                            {% if forloop.first %}
                                                {% for hidden in form.hidden_fields %}
                                                    {{ hidden }}
                                                {% endfor %}
                                            {% endif %}
                                            {{ field.errors.as_ul }}
                                            {{ field }}
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </table>
                    </div>

                    <br>

                    <input type="submit" class="btn btn-success btn-rounded btn-fw"
                           value="{% if mode == "add" %}Додати{% else %}Зберегти{% endif %}">
                    <a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-secondary btn-rounded btn-fw">Назад</button></a>
                </form>

            </div>
          </div>
        </div>
    </div>

    <script src="{% static 'formset/jquery.formset.js' %}"></script>

    <script type="text/javascript">
        $('.formset_row').formset({
            addText: 'Додати ще',
            deleteText: 'Видалити',
        });


        document.getElementById('dishForm').addEventListener("change", function(event) {
            var elem = event.target;

            if (elem.tagName === "SELECT") {
                regex = "id_.{0,}_set-(.{0,})-.{0,}";
                formId = elem.id.match(regex);
                id = elem.value;

                tr = elem.parentElement.parentElement;

                if (id) {
                    $.ajax({
                        url: "/manager/ingredient-name/get-units/" + id + "/",
                        type: "GET",
                        dataType: "json",
                        success: function(response) {
                            var sellingUnits = response.sellingUnits;

                            $(tr).find(".units").each(function() {
                               this.innerText = sellingUnits;
                            });
                        },
                        error: function(response) {}
                    });
                }

            }
        });

    </script>

{% endblock %}

templates/manager/home.html
{% extends "manager/base.html" %}
{% load static %}

{% block add_media %}
{#    <link rel="stylesheet" href="/static/css/ingredient.css"> #}
{% endblock %}

{% block content %}
    124
{% endblock %}

templates/manager/preparedDish-details.html
{% extends "manager/base.html" %}
{% load static %}

{% block add_media %}
{% endblock %}

{% block content %}
    <h1>Заготовлена страва "{{ dish.dish.name }}"</h1>


    <div class="row flex-grow">
        <div class="col-12">
          <div class="card">
            <div class="card-body">

                <br>
{#                {% if order.is_done %}#}
{#                    <button type="button" class="btn btn-success btn-rounded btn-fw" title="Натисніть, щоб змінити статус">Готово</button>#}
{#                {% else %}#}
{#                    <button type="button" class="btn btn-danger btn-rounded btn-fw" title="Натисніть, щоб змінити статус">Очікує</button>#}
{#                {% endif %}#}


                {% if dish.add_time|increaseTimeByMins:dish.dish.prepared_lifetime > timeNow %}
                    <button type="button" class="btn btn-success btn-rounded btn-fw">Придатно</button>
                {% else %}
                    <button type="button" class="btn btn-danger btn-rounded btn-fw">Зіпсовано</button>
                {% endif %}
                <a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-secondary btn-rounded btn-fw">Назад</button></a>
            </div>
          </div>
        </div>
    </div>

{% endblock %}