cafe/urls.py
from django.contrib import admin as admin_
from admin import *

from admin import urls as adminUrls
from manager import urls as managerUrls

from django.conf.urls import *
from cafe import views
from django.conf import settings
from django.urls import path, re_path, include
from django.contrib.auth.views import logout
from django.contrib.auth import views as django_auth_views
from django.contrib.auth import urls as authUrls

import rest_framework_jwt
#from rest_framework_jwt import views as rest_framework_jwt_views

from ingredients import views as ingredientsViews
from dishes import views as dishesViews
from _auth import views as authViews
from cafes import views as cafesViews
from authentication import views as authenticationViews
from statistics_ import views as statisticsViews

urlpatterns = [
    path('admin/', admin_.site.urls),
    #path('admin/', include(adminUrls.urlpatterns)),
    path("manager/", include(managerUrls.urlpatterns)),
    url(r"^add-ingredient/$", ingredientsViews.ingredient, name="add-ingredient"),
    url(r"^add-ingredientName/$", ingredientsViews.ingredientName, name="add-ingredientName"),
    url(r"^add-dish/$", dishesViews.addDish, name="add-dish"),
    url(r"^menu/$", dishesViews.dishesList, name="menu"),
    url(r"^dish/$", dishesViews.dishDescription, name="dishDescription"),
    url(r"^cart/$", dishesViews.cart, name="cart"),
    url(r"^accept-order/$", dishesViews.acceptOrder, name="acceptOrder"),
    path("order-details/<int:id>/", dishesViews.orderDetails, name="orderDetails"),
    url(r"^$", views.home, name="home"),

    # path("dish/", dishesViews.Dishes.as_view(), name="dish"),
    path("api/courier/orders_list/", dishesViews.OrdersListForCourier.as_view()),
    path("api/courier/order_details/<int:id>/", dishesViews.OrderDetailsForCourier.as_view()),
    path("api/courier/take_order/<int:id>/", dishesViews.CourierTakeOrder.as_view()),
    path("api/courier/cancel_order/<int:id>/", dishesViews.CourierCancelOrder.as_view()),
    path("api/courier/update_location/", dishesViews.CourierUpdateLocation.as_view()),
    path("api/courier/order/submit/<int:id>/", dishesViews.CourierSubmitOrder.as_view()),
    path("api/courier/order/my/", dishesViews.CourierMyOrders.as_view()),
    path("api/courier/order/total/", dishesViews.CourierTotalOrders.as_view()),

    path("api/courier/ingredients_transit_list/", dishesViews.IngredientsTransitListForCourier.as_view()),
    path("api/courier/ingredients_transit_details/<int:id>/", dishesViews.IngredientsTransitDetailsForCourier.as_view()),
    path("api/courier/take_ingredients_transit/<int:id>/", dishesViews.CourierTakeIngrTransit.as_view()),
    path("api/courier/cancel_ingredients_transit/<int:id>/", dishesViews.CourierCancelIngrTransit.as_view()),
    path("api/courier/ingredients_transit/total/", dishesViews.CourierTotalIngrTransit.as_view()),

    path("api/menu/dishes_list/<int:page>/", dishesViews.DishesList.as_view()),
    path("api/menu/categories_list/", dishesViews.DishCategoriesList.as_view()),
    path("api/menu/dish_description/<int:id>/", dishesViews.DishDetails.as_view()),

    path("api/order/create/", dishesViews.CreateOrder.as_view(), name="createOrder"),

    path("api/user/data/", authViews.UserData.as_view()),

    path("api/statistics/get/", statisticsViews.GetStatistics.as_view(), name="managerStatisticsGet"),


    url(r"^api/dish/$", dishesViews.api, name="apiDish"),
    url(r"^api/ingredient/$", ingredientsViews.api, name="apiIngredient"),

    url(r"^api/auth/", include("djoser.urls")),
    url(r"^api/auth/", include("djoser.urls.authtoken")),
    url(r"^api/auth/", include("djoser.urls.jwt")),
    #url(r"^api/auth/token/login1/", authenticationViews.token_request),

    url(r"^user/signup/$", authViews.signup, name="signup"),
    url(r"^user/login/$", django_auth_views.login, {'template_name': 'login.html'}, name="login"),
    url(r"^user/logout/$", logout, {"next_page": "/"}, name="logout"),
    url(r"^user/profile/$", authViews.profile, name="profile"),

    path('test/<int:id>/', dishesViews.test, name='room'),
    #url(r"^api/token/login/$", authenticationViews.CustomTokenCreateView.as_view()),


    # url(r"^api/login/$", rest_framework_jwt.views.obtain_jwt_token, name="apiLogin"),
]

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

locations/models.py
from django.db import models
from django.contrib.auth.models import User

class Location(models.Model):
    street_name = models.CharField("Вулиця", max_length=255, blank=True, null=True)
    home_details = models.CharField("Деталі житла", max_length=255, blank=True, null=True)
    lat = models.FloatField("Широта", blank=True, null=True)
    lon = models.FloatField("Довгота", blank=True, null=True)

    def __str__(self):
        return self.street_name or ""

    class Meta:
        verbose_name = "Локація"
        verbose_name_plural = "Локації"

class LastPosition(models.Model):
    user = models.OneToOneField(User, verbose_name="Корстувач", on_delete=models.CASCADE)
    lat = models.FloatField("Широта", blank=True, null=True)
    lon = models.FloatField("Довгота", blank=True, null=True)

    def __str__(self):
        return "%d" % self.id

    class Meta:
        verbose_name = "остання позиція"
        verbose_name_plural = "останні позиції"

_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm
from django.contrib.auth.models import User

from .models import *

class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="E-Mail", required=True, help_text="*")
    phone_number = forms.CharField(label="Номер телефона", max_length=13, required=False, help_text="")

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields.pop('password2')
        self.fields.pop('email')

        # for fieldname in ["username", "password1"]:
        #     self.fields[fieldname].help_text = "*"

        self.fields["first_name"].required = True
        self.fields["phone_number"].required = True

    class Meta:
        model = User
        fields = ("username", "phone_number", "password1", "first_name")


class ChangeForm(forms.ModelForm):
    # first_name = forms.CharField(label="Ім'я", max_length=20)
    # last_name = forms.CharField(label="Прізвище", max_length=40)
    # email = forms.EmailField(label="E-Mail", required=True, help_text="*")
    phone_number = forms.CharField(label="Номер телефона", max_length=13, required=False, help_text="",
                                   widget=forms.TextInput(attrs={'placeholder': 'Номер телефона'}))

    def __init__(self, *args, **kwargs):
        user = kwargs["instance"]
        profile = Profile.objects.get(user_id=user.pk)

        kwargs.update(initial={
            'phone_number': profile.phone_number
        })

        super(ChangeForm, self).__init__(*args, **kwargs)



    class Meta:
        model = User
        fields = ["first_name", "last_name", "phone_number"]

dishes/forms.py
from django.db import models
from django.forms import ModelForm
from django.forms import inlineformset_factory
from django.contrib.auth.models import User
from django.utils.timezone import now as time_now
from dishes.models import *

class DishForm(ModelForm):
    class Meta:
        model = Dish
        fields = ["name", "image", "description", "price"]

class DishIngredientsForm(ModelForm):
    class Meta:
        model = DishIngredients
        exclude = ()



DishFormSet = inlineformset_factory(Dish, DishIngredients, form=DishIngredientsForm, extra=2)

dishes/views.py
from django.http import *
from django.db import *
import json
import sys
import urllib.request
import datetime
import random
from cafe.settings import *
import math
from django.urls import reverse
from django.conf import settings
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import RequestContext
from django.views.decorators.csrf import csrf_protect
from django.views.generic.edit import FormView, CreateView
from django.core.files.base import ContentFile
from django.contrib.auth.decorators import *
from django.contrib.auth import get_user_model
from django.utils.timezone import now as time_now
from django.utils.safestring import mark_safe
from django.db.models import Count, F
from django.middleware import csrf
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.decorators.csrf import ensure_csrf_cookie
from _auth.views import getUserCookieValue
import itertools
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
import pytz
import copy
#from cafe.settings import MAPBOX
from django.utils import timezone
from django.db.models import Q

import operator
from cafe.views import get_ip

from django.contrib.auth.models import User
from authentication.serializers import UserSerializer
from rest_framework.views import APIView
from rest_framework.response import Response
from authentication.serializers import TokenCreateSerializer
from dishes.serializers import DishesSerializer
import djoser
from djoser.conf import settings
from djoser import utils
from rest_framework import generics, permissions, status, views, viewsets
from rest_framework.decorators import authentication_classes, permission_classes
from rest_framework.exceptions import APIException
import django.core.exceptions as DjangoExceptions
from django.shortcuts import render
from django.contrib.auth.models import User

from dishes.models import Dish
from dishes.serializers import *
from authentication.permissions import *

from _auth.models import Profile

from dishes.models import *
from dishes.admin import *
from dishes.forms import *
from ingredients.models import *
from locations.models import *




def dishesList(request):
    dishesList = Dish.objects.all().order_by("-id")
    csrf_token = csrf.get_token(request)

    return render(request, "menu.html", locals())


def dishDescription(request):
    return render(request, "dish.html", {
        "request": request
    })


@authentication_classes([])
@permission_classes([])
class DishesList(APIView):
    permission_classes = ()

    def get(self, request, page=1):

        dishesPerPage = 30

        cats = []
        if "cats" in request.GET.keys():
            cats_ = []
            cats_.append(list(request.GET.get("cats").split(",")))

            for list_ in cats_:
                for i in list_:
                    try:
                        cats.append(int(i))
                    except Exception: continue

        print(cats)

        filters = {}

        if cats:
            filters.update({"category__category_id__in": cats})

        limit = 999999
        if "limit" in request.GET.keys():
            try:
                limit = int(request.GET.get("limit"))
            except Exception: pass

        dishes = Dish.objects.filter(is_active=True, **filters)
        pagination = Paginator(list(set(dishes))[:limit], dishesPerPage)

        dishes = pagination.get_page(page)

        serializer = DishesSerializer(dishes, many=True)

        return Response(serializer.data)


@authentication_classes([])
@permission_classes([])
class DishDetails(APIView):
    permission_classes = ()

    def get(self, request, id):
        dish = get_object_or_404(Dish, id=id)
        serializer = DishesSerializer(dish)
        return Response(serializer.data)



@authentication_classes([])
@permission_classes([])
class DishCategoriesList(APIView):
    def get(self, request):
        categories = CategoryName.objects.all()
        categoriesSerializer = CategoryNameSerializer(categories,  many=True).data
        return Response(categoriesSerializer)


class OrdersListForCourier(APIView):
    permission_classes = (IsCourier,)

    def get(self, request):
        try: ordered_data = request.GET.get("ordered_data")
        except Exception: ordered_data = 0.0
        try: ordered_by = request.GET.get("ordered_by")
        except Exception: ordered_by = "id"

        ordered_data = 0.0 if ordered_data == None else ordered_data

        ORDERED_BY = ("id", "-id", "time", "-time")
        if ordered_by not in ORDERED_BY:
            ordered_by = "time"# ORDERED_BY[0]

        if ordered_by in ("time", "-time"):
            try: time = datetime.datetime.fromtimestamp(float(ordered_data)) if ordered_by != "-time" and not ordered_data else datetime.datetime.fromtimestamp(32536799999+1000000000)
            except: time = datetime.datetime.fromtimestamp(0.0) if ordered_by == 'time' else datetime.datetime.fromtimestamp(32536799999+1000000000)
        else: time = datetime.datetime.fromtimestamp(0.0)

        filters = {}
        if ordered_by == "id":
            filters.update({"id__gt": ordered_data})
        elif ordered_by == "-id":
            filters.update({"id__lt": ordered_data})
        elif ordered_by == "time":
            filters.update({"time__gt": time})
        elif ordered_by == "-time":
            filters.update({"time__lt": time})

        #undoneOrders = CouriersOrder.objects.filter(courier=request.user).exclude(status=CouriersOrder.STATUSES[3][0])
        undoneOrders = []

        #if not undoneOrders:
        if True:
            ordersParts = CouriersOrderPart.objects.filter(**filters, couriers_order__status=CouriersOrder.STATUSES[0][0]).order_by(ordered_by)
            ordersParts_ = list(set(ordersParts.values_list("couriers_order", flat=True)))[:99] #[:6]
            ordersParts = CouriersOrderPart.objects.filter(couriers_order_id__in=ordersParts_).order_by(ordered_by)

            if ordersParts:
                ordersToSerialize = []
                for i in ordersParts:
                    # print(i)
                    id = i.couriers_order.pk
                    order = CouriersOrder.objects.get(id=id)
                    if order not in ordersToSerialize:
                        ordersToSerialize.append(order)

                orders = OrderForCourierSerializer([*ordersToSerialize], many=True).data

                return Response(orders)
            else:
                raise APIException("notFound")
            # except:
            #     raise APIException("error")
        else:
            raise APIException("hasUndoneOrders")


class OrderDetailsForCourier(APIView):
    permission_classes = (IsCourier,)

    def get(self, request, id):
        print(id)
        try:
            order = CouriersOrder.objects.get(id=id)

            if order.status == CouriersOrder.STATUSES[0][0]:
                serializer = OrderDetailsForCourierSerializer(order)
                return Response(serializer.data)
            else:
                raise APIException("alreadyChosen")

        except DjangoExceptions.ObjectDoesNotExist:
            raise APIException("notFound")


class IngredientsTransitListForCourier(APIView):
    permission_classes = (IsCourier,)

    def get(self, request):
        List = CouriersIngredientsTransit.objects.filter(status=CouriersIngredientsTransit.STATUSES[0][0])
        serializedList = CouriersIngredientsTransitSerializer(List, many=True).data

        return Response(serializedList)


class IngredientsTransitDetailsForCourier(APIView):
    permission_classes = (IsCourier,)

    def get(self, request, id):
        cit = CouriersIngredientsTransit.objects.get(id=id)
        if cit.status == CouriersIngredientsTransit.STATUSES[0][0]:
            serializedList = CouriersIngredientsTransitSerializer(cit).data
            return Response(serializedList)
        else:
            return APIException("alreadyChosen")



class CourierTakeOrder(APIView):
    permission_classes = (IsCourier, ) # IsCourierFree

    def post(self, request, id):
        user = request.user
        order = get_object_or_404(CouriersOrder, id=id)

        if order.courier_id or order.status == "done":
            raise APIException("alreadyChosen")
        else:
            order.status = "chosen"
            order.courier_id = user.pk

            try:
                order.save()
                return Response({"status": "ok"})
            except:
                order.status = "not_chosen"
                order.courier_id = None
                order.save()
                return Response({"status": "fail"})


class CourierCancelOrder(APIView):
    permission_classes = (IsCourier,)

    def post(self, request, id):
        user = request.user
        order = get_object_or_404(CouriersOrder, id=id)
        statuses = [st[0] for st in CouriersOrder.STATUSES]

        if order.courier_id != user.pk:
            raise APIException("chosenByOther")
        elif order.status in statuses[3]:
            raise APIException("alreadyDone")
        elif order.status in statuses[2]:
            raise APIException("orderInProcess")
        else:
            try:
                order.status = statuses[0]
                order.courier_id = None
                order.save()
                return Response({"status": "ok"})
            except:
                order.status = statuses[1]
                order.courier_id = user.pk
                order.save()
                return Response({"status": "fail"})




templates/accept.html
{% extends "base.html" %}

{% block media %}
	<title>Червень | Підтвердити замовлення</title>
	<link rel="stylesheet" type="text/css" href="/css/accept.css">
    <style>
        /* Always set the map height explicitly to define the size of the div
         * element that contains the map. */
        {##map {#}
        {#    height: 500px;#}
        {#    width: 800px;#}
        {# }#}
    </style>
{% endblock %}

{% block content %}
    <input type="hidden" value="{% if lat %}
                                    {{ lat|floatWithDot }}
                                {% else %}
                                    50.249263
                                {% endif %}
                               " name="lat" id="id_lat">
    <input type="hidden" value="{% if lon %}
                                    {{ lon|floatWithDot }}
                                {% else %}
                                    28.6743508
                                {% endif %}
                               " name="lon" id="id_lon">
    <input type="hidden" value="{{ street_name }}" name="street_name" id="id_street_name">
    <div class="div-for-map">
        <div id="floating-panel">
            <input id="address" type="textbox" value="Житомир, {{ street_name }}">
            <input id="submit" type="button" value="ОБРАТИ">
        </div>
        <div id="map"></div>
    </div>
    <p align="center"><input type="text" name="home_details" id="id_home_details" placeholder="Номер квартири" value="{{ home_details }}"></p>
    <button type="button" id="submit-order" onclick="makeOrder()">Підтвердити</button>

<script>
function makeOrder() {

$("#submit-order").prop("disabled", true);

$.ajax({
    url: "{% url "createOrder" %}",
    type: "GET",
    dataType: "json",
    data: {
        "home_details": $("#id_home_details").val(),
        "street_name": $("#id_street_name").val(),
        "lat": $("#id_lat").val(),
        "lon": $("#id_lon").val()
    },
    success: function(response) {
        if (response) {
            console.log(response);
            // response = JSON.parse(response);
            if (response["status"] && response["status"] === "ok") {
                $.notify("Замовлення зареєстровано!", "success");
                var redirectTo = "{% url "profile" %}";
                if (response["order"]){
                    redirectTo = "/order-details/" + response["order"] + "/";
                }
                window.location.replace(redirectTo);
            }
            else {
                $.notify(response["status"], "error");
            }
        }
        else {
            $.notify("Помилка!", "error");
        }
    },
    error: function(response) {
        $.notify("Помилка сервера!", "error")
    }
});

$("#submit-order").prop("disabled", false);


}






var map, infoWindow, marker, address_components, cityBounds;

function initMap() {

cityBounds = new google.maps.LatLngBounds(
    new google.maps.LatLng(50.307491, 28.590374),
    new google.maps.LatLng(50.229317, 28.752060)
);

map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: parseFloat($("#id_lat").val()), lng: parseFloat($("#id_lon").val()) },
    zoom: 14
});
marker = new google.maps.Marker({
    map: map,
    position: {lat: parseFloat($("#id_lat").val()), lng: parseFloat($("#id_lon").val()) }
});
var geocoder = new google.maps.Geocoder();

document.getElementById('submit').addEventListener('click', function () {
    console.log("1");
    console.log(geocoder);
    console.log(map);
    console.log("-1");
    geocodeAddress(geocoder, map);
});
}


function geocodeAddress(geocoder, resultsMap) {
    var address = "Житомир, " + document.getElementById('address').value;
    google.maps.event.addListener(map, 'click', function (event) {
        placeMarker(event.latLng);
    });

    function placeMarker(location) {
        marker.setPosition(location);

    }

    console.log(cityBounds);

    geocoder.geocode({
        'address': address,
        bounds: cityBounds,
        componentRestrictions: {
            country:'Ukraine',
        }
    }, function (results, status) {
        if (status === 'OK') {
            address_components = results[0].address_components;
            console.log(address_components);
            console.log(address_components.long_name);

            var locationData = {};

            for (var ac = 0; ac < results[0].address_components.length; ac++) {

               var component = results[0].address_components[ac];

               if(component.types.includes('street_number')) {
                    console.log("street_number");
                    console.log(component);
                    locationData["street_number"] = component.long_name;
               }
               else if (component.types.includes('route')) {
                    console.log("route");
                    console.log(component);
                    locationData["street_name"] = component.long_name;
               }
               else if (component.types.includes('locality')) {
                    console.log("city");
                    console.log(component);
                    locationData["city"] = component.long_name;
               }
            }

            if (locationData["city"] && locationData["city"] === "Житомир") {
                if (locationData["street_name"] && locationData["street_number"]) {
                    resultsMap.setCenter(results[0].geometry.location);
                    marker.setPosition(results[0].geometry.location);
                    marker.map = resultsMap;
                    $("#id_lat").val(results[0].geometry.location.lat());
                    $("#id_lon").val(results[0].geometry.location.lng());
                    $("#id_street_name").val(
                        locationData["street_name"] + ", " + locationData["street_number"]
                    );
                }
                else {
                    $.notify("Не знайдено такої вулиці!");
                }
            }
            else {
                $.notify("Адреса знайдена, але поза Житомиром!");
            }
        } else {
            $.notify("Не знайдено!");
        }
    });
}


</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDEQqw183pZwuWHsjMM9IydQbqaxzuoU-s&callback=initMap&language=uk"
async defer></script>
{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block media %}
	<link rel="stylesheet" type="text/css" href="/css/profile.css">
{% endblock %}

{% block content %}
	<section>
		<img src="/img/profile-image.jpg">
	</section>
	<section>
		<form action="" method="POST">
                <button type="button" onclick="funcEdit();" class="edit">Редагувати</button>

                <div><font>{{ user.get_full_name }}</font>
                    {{ form.first_name }}
                    {{ form.last_name }}
                </div>

                <div>
                    <font>Тел.: {% if form.phone_number.value %}{{ form.phone_number.value }}{% else %}-{% endif %}</font>
                    {{ form.phone_number }}
                </div>

{#                <div>#}
{#                    <font>Пошта: {% if form.email.value %}{{ form.email.value }}{% else %}-{% endif %}</font>#}
{#                    {{ form.email }}#}
{#                </div>#}
                <button type="submit" onclick="funcSave();" class="save">Зберегти</button>
            </form>
	</section>
	<section>
		<h2>Мої замовлення:</h2>
        {% for order in orders %}
            <div>
                <a href="{% url "orderDetails" order.id %}"><h4>Замовлення #{{ order.id }}</h4></a>
                <h5>Статус: {% if order.status == "done" %}Виконано{% else %}В обробці{% endif %}</h5>

            </div>
        {% endfor %}
	</section>

<script type="text/javascript">

	function funcEdit() {
		$('article section:nth-of-type(2) div input').css({
			'display':'inline-block'
		});
		$('article section:nth-of-type(2) div font').css({
			'display':'none'
		});
		$('.save').css({
			'display':'block'
		});
		$('.edit').css({
			'display':'none'
		});
	}
</script>
{% endblock %}

templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Реєстрація</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="/static/Admin/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="/static/Admin/vendors/css/vendor.bundle.base.css">
  <link rel="stylesheet" href="/static/Admin/vendors/css/vendor.bundle.addons.css">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="/static/Admin/css/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="/static/Admin/images/favicon.png" />
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper auth-page">
      <div class="content-wrapper d-flex align-items-center auth register-bg-1 theme-one">
        <div class="row w-100">
          <div class="col-lg-4 mx-auto">
            <div class="auto-form-wrapper">
              <form method="POST" action="">


                <div class="form-group">
                    {% if form.username.errors %}
                        <ul class="list-ticked text-small">
                        {% for error in form.username.errors %}
                            <li class="text-danger"><span>{{ error|escape }}</span></li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                  <div class="input-group">
                    <input type="text" name="username" id="id_username" class="form-control" placeholder="Логін">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>


                <div class="form-group">
                    {% if form.first_name.errors %}
                        <ul class="list-ticked text-small">
                        {% for error in form.first_name.errors %}
                            <li class="text-danger"><span>{{ error|escape }}</span></li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                  <div class="input-group">
                    <input type="text" name="first_name" id="id_first_name" class="form-control" placeholder="Ваше ім'я, як до Вас звертатися">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>


                <div class="form-group">
                    {% if form.phone_number.errors %}
                        <ul class="list-ticked text-small">
                        {% for error in form.phone_number.errors %}
                            <li class="text-danger"><span>{{ error|escape }}</span></li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                  <div class="input-group">
                    <input type="text" name="phone_number" id="id_phone_number" class="form-control" maxlength="13" placeholder="Номер телефона">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>


                <div class="form-group">
                    {% if form.password1.errors %}
                        <ul class="list-ticked text-small">
                        {% for error in form.password1.errors %}
                            <li class="text-danger"><span>{{ error|escape }}</span></li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                  <div class="input-group">
                    <input type="password" name="password1" id="id_password1" class="form-control" placeholder="Пароль">
                    <div class="input-group-append">
                      <span class="input-group-text">
                        <i class="mdi mdi-check-circle-outline"></i>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <button class="btn btn-primary submit-btn btn-block">Зареєструватися</button>
                </div>
                <div class="text-block text-center my-3">
                  <span class="text-small font-weight-semibold">Вже зареєстровані?</span>
                  <a href="{% url "login" %}" class="text-black text-small">Увійти</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="/static/Admin/vendors/js/vendor.bundle.base.js"></script>
  <script src="/static/Admin/vendors/js/vendor.bundle.addons.js"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="/static/Admin/js/off-canvas.js"></script>
  <script src="/static/Admin/js/misc.js"></script>
  <!-- endinject -->
</body>

</html>